stages:
  - kubectl

logging:
  image: docker-registry.widas.de:5050/dockerregistry/common/kubectl-docker:v1
  stage: kubectl
  variables:
    KUBECONFIG_FILE: $wimcon1_loadtest_01_custom
  before_script:
    - mkdir -p /root/.kube && echo $KUBECONFIG_FILE | base64 -d > /root/.kube/config
  script:
    - kubectl delete -n wimcon1-loadtest-01-custom-services deployment cidaas-shopware-plugin
  only:
    - kubectl-branch