include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test
  - release

release:
  image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.5
  stage: release
  script:
    - semantic-release
  only:
    - master
