include:
  - template: Code-Quality.gitlab-ci.yml
  - project: widas/software-quality/gitlab-template-projects/widas-ci-templates
    file: common/github_sync.yml

stages:
  - test
  # - release
  - publish

# release:
#   image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.5
#   stage: release
#   script:
#     - semantic-release
#   only:
#     - master

# github_sync:
#   stage: publish
#   variables:
#     GIT_PROJECT_PATH: "Cidaas/cidaas-shopware-plugin"

github_sync:
  stage: publish
  image: bitnami/git
  variables:
    OBJECTS: "Dockerfile .gitlab-ci.yml scripts docker-compose.yml .releaserc temp"
    GIT_SERVER_HOST: "github.com"
    GITHUB_TARGET_BRANCH: "master"
    COMMIT_MESSAGE: "gitignore update"
    CACHE_UPDATE_COMMIT_MESSAGE: "gitignore cache update"
    GIT_PROJECT_PATH: "Cidaas/cidaas-shopware-plugin"
  script:
    - git config --global --add safe.directory $PWD
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email $GITLAB_USER_EMAIL
    - git checkout $GITHUB_TARGET_BRANCH
    - git remote -v >> temp
    - |
      if grep -q github temp;
        then :
      else
        git remote add github https://$GIT_SERVER_HOST/$GIT_PROJECT_PATH.git;
      fi
    - |
      ISFILECHANGED=false
      for FILE in $OBJECTS
      do
        if grep -Fxq $FILE .gitignore;
          then :
        else
          echo "$FILE" >> .gitignore;
          ISFILECHANGED=true
        fi
      done
      if $ISFILECHANGED;
      then
        git add .gitignore;
        git commit -m "$COMMIT_MESSAGE";
        git rm -r --cached .;
        git commit -am "$CACHE_UPDATE_COMMIT_MESSAGE"
      fi
    - git push https://$GITHUB_USER:$PAT@$GIT_SERVER_HOST/$GIT_PROJECT_PATH.git HEAD:$GITHUB_TARGET_BRANCH -f
    - git push https://$GITHUB_USER:$PAT@$GIT_SERVER_HOST/$GIT_PROJECT_PATH.git HEAD:$(git describe --abbrev=0 --tags)
  only:
    - master

